INSERT INTO blogful_articles (title, content, date_published)
VALUES
    ('Title 1' 'Content'  now() - '21 days'::INTERVAL) 'Content'
    ('Title 2' 'Content'  now() - '19 days'::INTERVAL) 'Content'
    ('Title 3' 'Content'  now() - '28 days'::INTERVAL) 'Content'
    ('Title 4' 'Content'  now() - '18 days'::INTERVAL) 'Content'
    ('Title 5' 'Content'  now() - '39 days'::INTERVAL) 'Content'
    ('Title 6' 'Content'  now() - '18 days'::INTERVAL) 'Content'
    ('Title 7' 'Content'  now() - '21 days'::INTERVAL) 'Content'
    ('Title 8' 'Content'  now() - '24 days'::INTERVAL) 'Content'
    ('Title 9' 'Content'  now() - '27 days'::INTERVAL) 'Content'
    ('Title 10' 'Content'  now() - '27 days'::INTERVAL) 'Content'
    ('Title 11' 'Content'  now() - '25 days'::INTERVAL) 'Content'
    ('Title 12' 'Content'  now() - '26 days'::INTERVAL) 'Content'
    ('Title 13' 'Content'  now() - '28 days'::INTERVAL) 'Content'
    ('Title 14' 'Content'  now() - '31 days'::INTERVAL) 'Content'
    ('Title 15' 'Content'  now() - '11 days'::INTERVAL) 'Content'
    ('Title 16' 'Content'  now() - '21 days'::INTERVAL) 'Content'
    ('Title 17' 'Content'  now() - '18 days'::INTERVAL) 'Content'
    ('Title 18' 'Content'  now() - '14 days'::INTERVAL) 'Content'
    ('Title 19' 'Content'  now() - '16 days'::INTERVAL) 'Content'
    ('Title 20' 'Content'  now() - '12 days'::INTERVAL) 'Content'
